# Workflow name
name: Build and Deploy Storybook React

# Event for the workflow
on: 
  push:
    branches:
      - gh-pages
    paths: # Trigger the action only when files change in the folders defined here
      - 'apps/react-web/src/**'

# List of jobs
jobs:
  build-and-deploy:
    # Operating system
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          # Whether to configure the token or SSH key with the local git config
          # Default: true
          persist-credentials: false
          
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm ci
          npm run build-storybook:react

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/storybook/react-web # The folder that the build-storybook script generates files.
          # Uses the provided scoped GitHub token by default ~~GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}~~
          # On by default ~~CLEAN: true # Automatically remove deleted files from the deploy branch~~
          target-folder: docs # The folder that we serve our Storybook files from
